### ISSUE TITLE
Missing LICENSE.md

### ISSUE THREAD

**Issue by GabrielDougherty** [nherbaut/cmake-gsoap-simple-example#1]
Hi, do you mind adding a license to this repository? Without a license, you retain all rights to this repository. https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by wi24rd** [comment]
Maybe public domain in law speaking?
It is short enough.
Maybe I'm kidding.

**Comment by nherbaut** [comment]
Fixed
